name: build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: unzip Enjou-1.21.1-source.zip
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 21 }
      - uses: gradle/actions/setup-gradle@v4
        with: { gradle-version: 8.10.2 }
      - run: cd Enjou && gradle build
      - uses: actions/upload-artifact@v4
        with: { name: Enjou-jar, path: Enjou/build/libs/*.jar }
